### ISSUE TITLE
tyresmoke nasal problems

### ISSUE THREAD

**Issue by FGDATA** [FGMEMBERS/E-jet-family#2]
> fg slows hardly down when retracting gear and putting out many many warnings like these:

[at /usr/share/games/flightgear/Aircraft/E-jet-family/Nasal/tyresmoke.nas, line 53
called from: /usr/share/games/flightgear/Nasal/globals.nas, line 119
Nasal runtime error: vector index 3 out of bounds (size: 3)
at /usr/share/games/flightgear/Aircraft/E-jet-family/Nasal/tyresmoke.nas, line 53
called from: /usr/share/games/flightgear/Nasal/globals.nas, line 119
Nasal runtime error: vector index 3 out of bounds (size: 3)
at /usr/share/games/flightgear/Aircraft/E-jet-family/Nasal/tyresmoke.nas, line 53
called from: /usr/share/games/flightgear/Nasal/globals.nas, line 119
Nasal runtime error: vector index 3 out of bounds (size: 3)
at /usr/share/games/flightgear/Aircraft/E-jet-family/Nasal/tyresmoke.nas, line 53
called from: /usr/share/games/flightgear/Nasal/globals.nas, line 119
Nasal runtime error: vector index 3 out of bounds (size: 3)
at /usr/share/games/flightgear/Aircraft/E-jet-family/Nasal/tyresmoke.nas, line 53
called from: /usr/share/games/flightgear/Nasal/globals.nas, line 119
Nasal runtime error: vector index 3 out of bounds (size: 3)
at /usr/share/games/flightgear/Aircraft/E-jet-family/Nasal/tyresmoke.nas, line 53
called from: /usr/share/games/flightgear/Nasal/globals.nas, line 119
Nasal runtime error: vector index 3 out of bounds (size: 3)
at /usr/share/games/flightgear/Aircraft/E-jet-family/Nasal/tyresmoke.nas, line 53
called from: /usr/share/games/flightgear/Nasal/globals.nas, line 119
Nasal runtime error: vector index 3 out of bounds (size: 3)
at /usr/share/games/flightgear/Aircraft/E-jet-family/Nasal/tyresmoke.nas, line 53
called from: /usr/share/games/flightgear/Nasal/globals.nas, line 119
Nasal runtime error: vector index 3 out of bounds (size: 3)
at /usr/share/games/flightgear/Aircraft/E-jet-family/Nasal/tyresmoke.nas, line 53
called from: /usr/share/games/flightgear/Nasal/globals.nas, line 119](url)

**Comment by FGDATA** [comment]
@D-ECHO 
I tested

With this small reversion 
https://github.com/FGMEMBERS/E-jet-family/tree/tyresmoke-bug
I see no problem anymore

With the master branch, I do get the nasal output errors, but I don't see impact on performace.

@Umoxfo 
The problem was specifically introduced over this commit
https://github.com/FGMEMBERS/E-jet-family/commit/b54fa419a2c502e6e8772a6b914db37ade976e81

**Comment by ghost** [comment]
Should be fixed by commit 6945dcd
