### ISSUE TITLE
Window shades

### ISSUE THREAD

**Issue by rx4** [FGMEMBERS/E-jet-family#6]
I can't get rid of the sunshades before the flight.

**Comment by legoboyvdlp** [comment]
The sunshade is a heads up display. Click on it to see things like speed etc :)

**Comment by legoboyvdlp** [comment]
Are you trying to run it with Rembrandt or ALS? What is your graphics card model? AMD cards tend to be problematic.

**Comment by rx4** [comment]
Rembrandt is what i used and it caused that problem I think.

**Comment by rx4** [comment]
well I usea rembradt. Rembradt causes so many problems so yeah sorry for the issue. I realized that it is best if i dont use rembradt the default renderer is the best choice. Rembradt also caused a problem on the 737-900er.
